export const CREATE_PURCHASE = "PURCHASE/CREATE_PURCHASE";
export const ADD_PRODUCTS = "PURCHASE/ADD_PRODUCTS";
export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
